var picDic = {
    "AGS_Aguascalientes": ["https://livitmexico.com/assets/img/estados/aguascalientes/isla-san-marcos.jpg", "https://api-cms.gayosso.com/storage/agencias/ags_agencia_1.jpg", "https://pueblomx.com/wp-content/uploads/2022/10/aniversario.jpg", "https://livitmexico.com/assets/img/estados/aguascalientes/el-sabinal.jpg"],
    "AGS_Asientos": ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/1e/e7/dd/photo7jpg.jpg?w=700&h=500&s=1", "https://www.asere.com/wp-content/uploads/2020/06/Oaxaca-Me%CC%81xico.jpg", "https://travmex.com/wp-content/uploads/2022/02/Tacos-al-Pastor-1-cropped-700x500.jpg", "https://travmex.com/wp-content/uploads/2022/02/Mexican-beach-destination-1-700x500.jpg"],
    "AGS_Calvillo": ["https://mexicodesconocidoviajes.mx/wp-content/uploads/2020/09/MD_CALVILLO_RUTA-DEL-ARTISTA_PJ_ok-700x500.jpg", "https://api-cms.gayosso.com/storage/cementerios/san_ignacio_1.1.jpg", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/76/c8/9c/worth-a-25-minute-drive.jpg?w=700&h=500&s=1", "https://neomexicanismos.com/wp-content/uploads/2016/12/calvillo-800x600-700x500.jpg"],
    "AGS_Cosio": ["https://i0.wp.com/labrecha.me/wp-content/uploads/2022/07/Muestra-Nacional-de-Danzo%CC%81n-0-2.jpg?fit=700%2C500&ssl=1", "https://reportajesmetropolitanos.com.mx/morelos15.jpg", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/e3/52/e2/cosio-valtellino.jpg?w=700&h=500&s=1", "https://infogruas.com.mx/wp-content/uploads/gruas-en-cosio.jpg"],
    "AGS_El_Llano": ["https://informativoelvalledeaguascalientes.online/wp-content/uploads/2022/10/IMG-20221022-WA0127.jpg", "https://s2.wklcdn.com/image_158/4762285/45724419/30081125Master.jpg", "https://s0.wklcdn.com/image_124/3722050/47103043/31074318Master.jpg" ,"https://s0.wklcdn.com/image_205/6160083/47322186/31368858Master.jpg"],
    "BCN_Ensenada": ["https://1.bp.blogspot.com/-Jo-EwfA7a1w/Xd9wiGN8_wI/AAAAAAAAfc4/jdmAqWBrprUhBOIdYt9VvQB5piJ-j9bJwCLcBGAsYHQ/s1600/PLAYA-ENSENADA-GRANDE-LA-PAZ-VIAJA-BONITO-1.jpg", "https://www.puertoensenada.com.mx/upl/sec/movimiento_portuario_2017.jpg", "https://xpectrofm.com/wp-content/uploads/2022/08/Seguridad-controlada-75.jpg", "https://ensenadahoy.com/pub/publicaciones/org_22837.jpg"],
    "BCN_Mexicali": ["https://www.gob.mx/cms/uploads/image/file/731965/FOo8R6UWQAkmEzd.jpg", "https://live.staticflickr.com/4809/31272737717_0005b2f025_h.jpg", "https://live.staticflickr.com/65535/49347198467_4060288a40_h.jpg", "https://lh3.googleusercontent.com/p/AF1QipOhwad7a7CNiBtqXisIk1VwybV3NQ8x7nk_tv_L=s1600-w1920"],
    "BCN_Playas_de_Rosarito": ["https://i0.wp.com/tijuananoticias.info/bc/wp-content/uploads/2022/11/01cda380-b788-43f9-a091-fcc5a57c77b5.jpg?ssl=1", "https://media.vogue.mx/photos/5fde389155efa4fbe27605e1/master/w_1600%2Cc_limit/playa-Rosarito-Me%25CC%2581xico.jpg", "https://seturistabc.com/wp-content/uploads/2022/09/hotel-rosarito-city-express-alberca-2.jpg", "http://gcadena.com/inmobiliaria/wp-content/uploads/2018/08/209549-rosarito-beach.jpg"],
    "BCN_Tecate": ["https://4.bp.blogspot.com/-omuGaFeiCa0/XGZY-vmNvEI/AAAAAAAABMs/_mNT6peagnkW7_rXY4xD6p09TDJ3k-zfACKgBGAs/s1600/Tecate%2B-%2BBaja%2BCalifornia%2B%25285%2529.jpg", "https://cadenanoticias.com/assets/article/00115514/20210521_mcBam9Ju50.jpeg", "http://wsextbc.ebajacalifornia.gob.mx/CdnBC/api/Imagenes/ObtenerImagenDeSistema?sistemaSolicitante=AdmonPortal/4/6846/20220822&nombreArchivo=se.png&descargar=false", "https://static01.nyt.com/images/2017/04/30/travel/30BAJA/30BAJA-videoSixteenByNineJumbo1600.jpg"],
    "BCN_Tijuana": ["https://amotijuana.com/wp-content/uploads/2018/04/67776-Centro-Cultural-Tijuana.jpg", "https://cadenanoticias.com/assets/article/00129216/20220205_EnOTiw4pmx.jpeg", "https://cadenanoticias.com/assets/article/00140946/20220831_YbK7jZhmQl.jpeg", "https://static.jornadabc.com.mx/wp-content/uploads/2022/04/viviendas-en-Tijuana.jpeg"],
    "BCS_Comondu": ["https://biolafmx.com/wp-content/uploads/2021/10/Actividad-agricola-en-Comondu-Baja-California-Sur-portada.jpg", "https://hoybcs.com/wp-content/uploads/2022/07/8ABD4449-EF49-4BA3-A8D3-6BA7F1321AC5.jpeg", "https://i0.wp.com/panoramaagrario.com/wp-content/uploads/2014/09/ORGANICA.jpg?fit=1600%2C900&ssl=1", "https://s2.wklcdn.com/image_218/6550189/59729577/39847715Master.jpg"],
    "BCS_La_Paz": ["https://1.bp.blogspot.com/-Jo-EwfA7a1w/Xd9wiGN8_wI/AAAAAAAAfc4/jdmAqWBrprUhBOIdYt9VvQB5piJ-j9bJwCLcBGAsYHQ/s1600/PLAYA-ENSENADA-GRANDE-LA-PAZ-VIAJA-BONITO-1.jpg", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/5b/cc/9c/costa-baja-resort.jpg?w=1600&h=900&s=1/", "https://www.peterktravels.com/wp-content/uploads/2014/02/IMG_6753b.jpg", "https://lh5.googleusercontent.com/p/AF1QipPu6aAYLJI-0rCNk0_7dqblH_9n3GZ9RNvRzKvA=s1600"],
    "BCS_Loreto": ["https://tpcdanzantebay.mx/wp-content/uploads/2018/07/home_islands.jpg", "https://tpcdanzantebay.mx/wp-content/uploads/2020/06/home_getting_here.jpg", "https://loretorubiosportfishing.com/mx/public/uploads/destination-20.jpg", "https://a0.muscache.com/pictures/3efa5cc5-3d2a-490d-8c49-f7b95015081c.jpg"],
    "BCS_Los_Cabos": ["https://villaexperience.com/wp-content/uploads/2020/11/hacienda-beach-condo-cabo-1-51.jpg", "https://cdn.photos.sparkplatform.com/cab/20221105195957887154000000-o.jpg", "https://images2.imgbox.com/54/23/i8NpfCOy_o.jpeg", "https://indemloscabos.gob.mx/wp-content/uploads/2021/11/4-6.jpg"],
    "BCS_Mulege": ["https://lh5.googleusercontent.com/p/AF1QipO6Goo943cO17rDp0i-2hKpeKHqH292IcWqBKdb=s1600", "https://lh5.googleusercontent.com/p/AF1QipMVVic4r0UU_TlviVkA4DmsIyKQfbERqX9nZlkA=s1600", "http://2.bp.blogspot.com/-cLZDmO8qNjw/UnWUFjX-DkI/AAAAAAABlNs/xFw7vkBsCgk/s1600/P1180736.JPG", "https://lh5.googleusercontent.com/p/AF1QipOrYFT33u5TFLh1Cb_S0nzKIKJGyRFhe9DFGfgc=s1600"],
    "CAM_Calakmul": ["https://lugares.inah.gob.mx/images/zonas/media/1661/_thumb1/226_A_000.jpg", "https://cnnespanol.cnn.com/wp-content/uploads/2022/10/221027160200-inah-hallazgos-calakmul-zona-arqueologica-mayas-redaccion-mexico-full-169.jpg?quality=100&strip=info", "https://villacalakmul.mx/images/portada2.jpeg", "https://2.bp.blogspot.com/-cjj4PH6Fpr8/XDKwpCsVhUI/AAAAAAAADqY/_24eKDzmUoUvvNAJX5JA7Hak7tl3QjCbgCLcBGAs/s1600/I.%2BVuelvo%2Ba%2Bti.jpg"],
    "CAM_Calkini": ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/cc/15/55/palapa-al-final-del-sendero.jpg?w=700&h=500&s=1", "https://livitmexico.com/assets/img/estados/campeche/calkini.jpg", "https://livitmexico.com/assets/img/estados/campeche/isla-aguada.jpg", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/fc/9c/8a/iglesia.jpg?w=700&h=500&s=1"],
    "CAM_Campeche": [],
    "CAM_Candelaria": [],
    "CAM_Palizada": [],
    "COA_Abasolo": [],
    "COA_Acuna": [],
    "COA_Allende": [],
    "COA_Arteaga": [],
    "COA_Candela": [],
    "COL_Armeria": [],
    "COL_Colima": [],
    "COL_Comala": [],
    "COL_Coquimatlan": [],
    "COL_Cuauhtemoc": [],
    "CHP_Acacoyagua": [],
    "CHP_Acala": [],
    "CHP_Acapetahua": [],
    "CHP_Aldama": [],
    "CHP_Altamirano": [],
    "CHI_Ahumada": [],
    "CHI_Aldama": [],
    "CHI_Allende": [],
    "CHI_Aquiles_Serdan": [],
    "CHI_Ascension": [],
    "DIF_Alvaro_Obregon": [],
    "DIF_Azcapotzalco": [],
    "DIF_Benito_Juarez": [],
    "DIF_Coyoacan": [],
    "DIF_Cuajimalpa_de_Morelos": [],
    "DUR_Canatlan": [],
    "DUR_Canelas": [],
    "DUR_Coneto_de_Comonfort": [],
    "DUR_Cuencame": [],
    "DUR_Durango": [],
    "GTO_Abasolo": [],
    "GTO_Acambaro": [],
    "GTO_Apaseo_el_Alto": [],
    "GTO_Apaseo_el_Grande": [],
    "GTO_Atarjea": [],
    "GRO_Acapulco_de_Juarez": [],
    "GRO_Acatepec": [],
    "GRO_Ahuacuotzingo": [],
    "GRO_Ajuchitlan_del_Progreso": [],
    "GRO_Alcozauca_de_Guerrero": [],
    "HGO_Acatlan": [],
    "HGO_Acaxochitlan": [],
    "HGO_Actopan": [],
    "HGO_Agua_Blanca_de_Iturbide": [],
    "HGO_Ajacuba": [],
    "JAL_Acatic": [],
    "JAL_Acatlan_de_Juarez": [],
    "JAL_Ahualulco_de_Mercado": [],
    "JAL_Amacueca": [],
    "JAL_Amatitan": [],
    "OMX_Acambay_de_Ruiz_Castaneda": [],
    "OMX_Acolman": [],
    "OMX_Aculco": [],
    "OMX_Almoloya_de_Alquisiras": [],
    "OMX_Almoloya_de_Juarez": [],
    "MIC_Acuitzio": [],
    "MIC_Aguililla": [],
    "MIC_Alvaro_Obregon": [],
    "MIC_Angamacutiro": [],
    "MIC_Angangueo": [],
    "MOR_Amacuzac": [],
    "MOR_Atlatlahucan": [],
    "MOR_Axochiapan": [],
    "MOR_Ayala": [],
    "MOR_Coatlan_del_Rio": [],
    "NAY_Acaponeta": [],
    "NAY_Ahuacatlan": [],
    "NAY_Amatlan_de_Canas": [],
    "NAY_Bahia_de_Banderas": [],
    "NAY_Compostela": [],
    "NLE_Abasolo": [],
    "NLE_Agualeguas": [],
    "NLE_Allende": [],
    "NLE_Anahuac": [],
    "NLE_Apodaca": [],
    "OAX_Abejones": [],
    "OAX_Acatlan_de_Perez_Figueroa": [],
    "OAX_Animas_Trujano": [],
    "OAX_Asuncion_Cacalotepec": [],
    "OAX_Asuncion_Cuyotepeji": [],
    "PUE_Acajete": [],
    "PUE_Acateno": [],
    "PUE_Acatlan": [],
    "PUE_Acatzingo": [],
    "PUE_Acteopan": [],
    "QRO_Amealco_de_Bonfil": [],
    "QRO_Arroyo_Seco": [],
    "QRO_Cadereyta_de_Montes": [],
    "QRO_Colon": [],
    "QRO_Corregidora": [],
    "ROO_Bacalar": [],
    "ROO_Benito_Juarez": [],
    "ROO_Cozumel": [],
    "ROO_Felipe_Carrillo_Puerto": [],
    "ROO_Isla_Mujeres": [],
    "SLP_Ahualulco": [],
    "SLP_Alaquines": [],
    "SLP_Aquismon": [],
    "SLP_Armadillo_de_los_Infante": [],
    "SLP_Axtla_de_Terrazas": [],
    "SIN_Ahome": [],
    "SIN_Angostura": [],
    "SIN_Badiraguato": [],
    "SIN_Choix": [],
    "SIN_Concordia": [],
    "SON_Aconchi": [],
    "SON_Agua_Prieta": [],
    "SON_Alamos": [],
    "SON_Altar": [],
    "SON_Arivechi": [],
    "TAB_Balancan": [],
    "TAB_Cardenas": [],
    "TAB_Centla": [],
    "TAB_Centro": [],
    "TAB_Comalcalco": [],
    "TAM_Victoria": [],
    "TAM_Aldama": [],
    "TAM_Altamira": [],
    "TAM_Antiguo_Morelos": [],
    "TAM_Burgos": [],
    "TLX_Acuamanala_de_Miguel_Hidalgo": [],
    "TLX_Amaxac_de_Guerrero": [],
    "TLX_Apetatitlan_de_Antonio_Carvajal": [],
    "TLX_Apizaco": [],
    "TLX_Atlangatepec": [],
    "VER_Acajete": [],
    "VER_Acatlan": [],
    "VER_Acayucan": [],
    "VER_Actopan": [],
    "VER_Acula": [],
    "YUC_Abala": [],
    "YUC_Acanceh": [],
    "YUC_Akil": [],
    "YUC_Baca": [],
    "YUC_Bokoba": [],
    "ZAC_Apozol": [],
    "ZAC_Apulco": [],
    "ZAC_Atolinga": [],
    "ZAC_Benito_Juarez": [],
    "ZAC_Calera": [],
}
